# Generated by Django 5.1.3 on 2024-12-06 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voting", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="election",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candidates",
                to="voting.election",
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="election",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="election",
            name="end_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="election",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="election",
            name="start_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="vote",
            name="candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes",
                to="voting.candidate",
            ),
        ),
        migrations.AlterField(
            model_name="vote",
            name="election",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes",
                to="voting.election",
            ),
        ),
        migrations.AlterField(
            model_name="vote",
            name="encrypted_vote",
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name="vote",
            name="voter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
